name: Convert README to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc, LaTeX, and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra librsvg2-bin
      - name: Debug Output
        run: |
          ls -l $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/README.md
          cat $GITHUB_WORKSPACE/template.tex
      - name: Convert README to PDF
        run: |
          pandoc $GITHUB_WORKSPACE/README.md -o $GITHUB_WORKSPACE/README.pdf --pdf-engine=pdflatex \
            -V geometry:margin=1in \
            -V documentclass:report \
            -V lang=en-US \
            -V fontsize=12pt \
            -V papersize=a4 \
            -V inputenc=utf8 \
            -V fontfamily=mathpazo \
            -V fontfamilyoptions=sc \ 
            --template=$GITHUB_WORKSPACE/template.tex
          
      - name: Upload PDF to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: README_PDF
          path: README.pdf
