name: Convert README to PDF

on:
  push:
    branches:
      - main  # Change this based on your default branch

jobs:
  convert-to-pdf:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc, LaTeX, and Dependencies
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install pandoc
            brew install mactex-no-gui
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install pandoc
            choco install miktex
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra librsvg2-bin
          fi

      - name: Convert README to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=pdflatex \
            -V geometry:margin=1in \
            -V documentclass:report \
            -V lang=en-US \
            -V fontsize=12pt \
            -V papersize=a4 \
            -V inputenc=utf8 \
            -V fontfamily=mathpazo \
            -V fontfamilyoptions=sc

      - name: Commit and Push Changes
        run: |
          git config --global user.name "yurytrifonov"
          git config --global user.email "jutrifonov@uchicago.edu"
          git checkout -b update-pdf
          git add README.pdf
          git commit -m "Update README.pdf"
          git push origin update-pdf

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update README.pdf"
          commit-message: "Automatically update README.pdf"
          branch: update-pdf
