name: Convert README to PDF and Commit

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/README.pdf'  # Prevent loops

jobs:
  convert_and_commit_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic librsvg2-bin wget

      # Create a temporary copy of README.md so the original is not modified.
      - name: Create a temporary copy of README.md for PDF conversion
        run: cp README.md README_pdf.md

      # Download remote SVG badges.
      - name: Download remote SVG badges
        run: |
          wget -O actions_badge.svg "https://github.com/jutrifonov/sreg/actions/workflows/R-CMD-check.yaml/badge.svg"
          wget -O codecov_badge.svg "https://codecov.io/github/jutrifonov/sreg/graph/badge.svg?token=KAUXB0ETCA"
          VERSION_URL=$(grep -oE 'https://img.shields.io/badge/sreg-v[^)]*' README.md | head -n 1)
          echo "Detected version badge URL: $VERSION_URL"
          wget -O version_badge.svg "$VERSION_URL"
          wget -O cran_badge.svg "https://img.shields.io/badge/CRAN-v.1.0.1-orange?logo=R&labelColor=2A2523"

      # Convert the downloaded SVG badges to PNG at a higher resolution.
      
      - name: Convert downloaded SVG badges to PNG
        run: |
          for badge in actions_badge codecov_badge version_badge cran_badge; do
          if ! rsvg-convert -w 600 ${badge}.svg -o ${badge}.png; then
          echo "Failed to convert ${badge}.svg to PNG"
          exit 1
          fi
          file ${badge}.png
          done
      - name: Debug image file content (if any fails)
        run: head -n 10 actions_badge.png || true

      # Update the temporary README so that badge URLs point to the local PNG files.
      - name: Replace badge URLs in README_pdf.md
        run: |
          sed -i -E 's|https://github.com/.*/actions/workflows/[^)]*|actions_badge.png|g' README_pdf.md
          sed -i -E 's|https://codecov.io/[^)]*|codecov_badge.png|g' README_pdf.md
          sed -i -E 's|https://img\.shields\.io/badge/sreg-v[^)]*|version_badge.png|g' README_pdf.md
          sed -i -E 's|https://img\.shields\.io/badge/CRAN-v[^)]*|cran_badge.png|g' README_pdf.md

      - name: Print badge lines for debugging
        run: grep -i 'badge' README_pdf.md || echo "No badge lines found"
        
      # Convert the modified Markdown file to PDF.
      - name: Convert Markdown to PDF
        run: |
          pandoc README_pdf.md \
            --pdf-engine=xelatex \
            --from markdown+raw_html+raw_tex \
            -V geometry:"margin=1in" \
            -V colorlinks=true \
            -V monofont="DejaVu Sans Mono" \
            -V header-includes:"\setkeys{Gin}{height=0.5cm,keepaspectratio}" \
            -o .github/README.pdf

      - name: Setup Git Config
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

      - name: Commit and Push PDF
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main
          git reset --soft origin/main
          git add .github/README.pdf
          git commit -m "Update README.pdf in .github directory" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


