name: Convert README to PDF

on:
  push:

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update packages and Install Pandoc, LaTeX, SVG conversion, and DejaVu fonts
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-xetex texlive-fonts-recommended texlive-extra-utils texlive-latex-extra librsvg2-bin fonts-dejavu

      - name: Convert README to PDF using XeLaTeX with DejaVu Font
        run: pandoc README.md --pdf-engine=xelatex --variable mainfont="DejaVu Sans Mono" -o README.pdf

      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Update README.pdf" or echo "No changes to commit"
          git push


