name: Convert README to PDF

on:
  push:

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc, LaTeX, and SVG conversion packages
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          sudo apt-get install librsvg2-bin

      - name: Convert README to PDF using XeLaTeX
        run: pandoc README.md --pdf-engine=xelatex -o README.pdf

      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Update README.pdf" || echo "No changes to commit"
          git push

