name: Convert README to PDF

on:
  push:

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX packages
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Convert README to PDF
        run: pandoc README.md -o README.pdf

      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Update README.pdf" || echo "No changes to commit"
          git push
