name: Convert README to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Convert to PDF
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          pandoc README.md -o README.pdf

      - name: Upload PDF to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: README_PDF
          path: README.pdf
