name: Update PDF

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

      - name: Custom script to generate PDF
        run: |
          echo "Add your commands here"
          # Example: pandoc -s README.md -o README.pdf

      - name: Commit and Push
        run: |
          git add .
          git commit -m 'Update PDF' || echo 'No changes to commit'
          git push --set-upstream origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}




