name: Generate PDF from README

on:
  push:
    branches: [main, master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert README.md to PDF
      run: |
        pandoc README.md -o README.pdf
