name: Generate PDF from README

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert README.md to PDF
      run: |
        pandoc README.md -o README.pdf
    ```

This workflow will run on every push to the main branch and will use Pandoc to convert README.md to README.pdf.

